"""empty message

Revision ID: 628990a5db4e
Revises: b09b87544e15
Create Date: 2018-10-15 19:37:42.335466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628990a5db4e'
down_revision = 'b09b87544e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
