"""empty message

Revision ID: 82ca4d0a3c06
Revises: 
Create Date: 2018-11-29 13:00:27.010123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ca4d0a3c06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('jit_tasking', sa.Boolean(), nullable=True),
    sa.Column('recurrence_resched_tasking', sa.Boolean(), nullable=True),
    sa.Column('streaks', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
