"""empty message

Revision ID: eed5d4a8e0b9
Revises: 
Create Date: 2018-12-25 11:04:38.298064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed5d4a8e0b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('jit_feature', sa.Boolean(), nullable=True),
    sa.Column('recurrence_resch_feature', sa.Boolean(), nullable=True),
    sa.Column('streaks_feature', sa.Boolean(), nullable=True),
    sa.Column('in_line_comment_feature', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
